# default config for pdf2img-ocr, trigger it by adding --load-default parameter
vision_model = "gemma4:e4b"
refine_model = "gpt-oss:120b-cloud"
action = "deep"      # clean | summary | deep | skip
lang = "en"          # en | id | original | etc.
level = "beginner"   # beginner | intermediate | advanced
